### ISSUE TITLE
Feature request: add branch-tag-latest

### ISSUE THREAD

**Issue by yacoob** [crazy-max/ghaction-docker-meta#11]
For my [repo](http://github.com/yacoob/conf) I'd like to mark new image as `latest` for every build off the main branch. It'd be nice to have `branch-tag-latest` together with `branch-tag` which would add `latest` tag if `github.ref` would match the specified pattern.

**Comment by crazy-max** [comment]
@gbaeke 

> I'd like to mark new image as latest for every build off the main branch.

Might not be necessary to add another input for that I think. Instead you could use:

```yml
tags: |
  ${{ steps.docker_meta.outputs.tags }}
  ${{ github.ref == 'refs/heads/main' && 'name/app:main' || '' }}
```

**Comment by olevitt** [comment]
> @gbaeke
> 
> > I'd like to mark new image as latest for every build off the main branch.
> 
> Might not be necessary to add another input for that I think. Instead you could use:
> 
> ```yaml
> tags: |
>   ${{ steps.docker_meta.outputs.tags }}
>   ${{ github.ref == 'refs/heads/main' && 'name/app:main' || '' }}
> ```

I had the same issue / request as @yacoob and this worked perfectly.  
In my case :  
```
tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ github.ref == 'refs/heads/master' && 'olevitt/example-repo:latest' || '' }}
```
