### ISSUE TITLE
Add appending option to tags

### ISSUE THREAD

**Issue by kereis** [crazy-max/ghaction-docker-meta#13]
Let's say you build multiple distro flavors of your Docker image, e. g. one in Ubuntu (main) and one in Alpine.
Meanwhile it's fine to use the usual tagging for the main image, is there a way of setting a "base tag" or a "tag" to be appended? In this case, for the Alpine flavor, instead of `latest`, using `alpine`, `x.x.x-alpine` etc. is more appropriate.

**Comment by mblaschke** [comment]
also interested in prefix/suffix

**Comment by jgustie** [comment]
I thought I could fake this with `sep-tags: -alpine,` in the meta action and setting `tags: ${{ steps.docker_meta.outputs.tags }}-alpine` in the build push action, however it looks like the `sep-tags` is also being used on the labels which is causing the image to get a single label.

**Comment by slimcdk** [comment]
Also interested in tag pre/suffixes

**Comment by LongLiveCHIEF** [comment]
I'm going to open an issue or two, and even see about contributing a few of the features from an action I wrote a while back ([HackerHappyHour/tagging-strategy](https://github.com/HackerHappyHour/tagging-strategy) that has the options being asked about here.

**Comment by whyman** [comment]
+1 for prefix/suffix on tags

**Comment by lpil** [comment]
Hi all! Is there a workaround for this?

**Comment by humenius** [comment]
> Hi all! Is there a workaround for this?

Hey, you can take a look at [my workflow file for traefik-certs-dumper](https://github.com/humenius/traefik-certs-dumper/blob/develop/.github/workflows/release.yml). I haven't tested it throughly though.

**Comment by LongLiveCHIEF** [comment]
You can use the [HackerHappyHour/tagging-strategy@v3](https://github.com/marketplace/actions/tagging-strategy) action for this in the meantime while #30 is being considered.

For live examples of this see https://github.com/OctoPrint/octoprint-docker/blob/master/.github/workflows/octoprint-release.yml
