### ISSUE TITLE
Should 'latest' be given it's own input as a 'boolen'?

### ISSUE THREAD

**Issue by LongLiveCHIEF** [crazy-max/ghaction-docker-meta#19]
The generation of `latest` seems somewhat problematic.  There no way to directly _prevent_  `latest` from being generated in many cases, 

Would it be better, easier, and more straightforware to remove the `latest` generation logic entirely the way it is now, and just make it a `boolean` input type so that users could specify whether or not to generate the `latest` explicitly regardless of the event?

**Comment by LongLiveCHIEF** [comment]
Actually, i'm starting to wonder why it wouldn't just be better if the user passed in the appropriate context all together instead of trying to determine the context based on the event type.

**Comment by LongLiveCHIEF** [comment]
related comment https://github.com/crazy-max/ghaction-docker-meta/issues/18#issuecomment-733973336

**Comment by crazy-max** [comment]
@LongLiveCHIEF #23 should fix your issue (new input called `tag-latest`).
Can be tested with `uses: crazy-max/ghaction-docker-meta:master`.
