### ISSUE TITLE
Should tag-semver work without patch version?

### ISSUE THREAD

**Issue by EnricoMi** [crazy-max/ghaction-docker-meta#20]
Some small projects might decide not to release patch versions but still follow the semantic versioning rules. Can this action work with `tag-semver: v${{major}}` on tags like v1.0 to produce `v1`? Currently, it does not seem to:

https://github.com/EnricoMi/publish-unit-test-result-action/runs/1474478085?check_suite_focus=true
```
Run crazy-max/ghaction-docker-meta@v1
  with:
    images: ghcr.io/EnricoMi/publish-unit-test-result-action
    tag-sha: true
    tag-semver: {{raw}}
  v{{major}}.{{minor}}
  v{{major}}
  
    tag-edge: false
    tag-match-group: 0
    tag-match-latest: true
    tag-schedule: nightly
    github-token: ***
Context info
Docker image version
  v1.6
Docker tags
  ghcr.io/enricomi/publish-unit-test-result-action:v1.6
  ghcr.io/enricomi/publish-unit-test-result-action:latest
  ghcr.io/enricomi/publish-unit-test-result-action:sha-f1387c5
```

**Comment by crazy-max** [comment]
@EnricoMi 

> Currently, it does not seem to

That's because `v1.6` tag is not a [valid semver](https://semver.org/). Should have been `v1.6.0` to be a valid one. I will add a warning message in case `tag-semver` is used but input tag is not a vliad semver.
