### ISSUE TITLE
Select/Change order of tags.

### ISSUE THREAD

**Issue by Vilsol** [crazy-max/ghaction-docker-meta#27]
If you have `latest` and/or `sha` tagging enabled, then they get pushed to the registry last. Due to how github treats the last image pushed as the "latest" one, it shows it as first in every list and reference to that package.

This can get very confusing if you are looking at a list of packages e.g. here: https://github.com/orgs/restorecommerce/packages

It would be great if the `latest` and `sha` tags would be first in the list of tagged images, and the semver ones last. You could also provide an option to toggle this functionality or even pick the order.

**Comment by Vilsol** [comment]
I don't understand how this is a stale issue?

**Comment by crazy-max** [comment]
@Vilsol That's a UI/UX on design GitHub and I don't think this should be handled here. But we could handle the order through #30.
