### ISSUE TITLE
tag-latest: true not working

### ISSUE THREAD

**Issue by felipecrs** [crazy-max/ghaction-docker-meta#41]
Please see this build as example:

https://github.com/felipecrs/jenkins-agent-dind/runs/1812044006

Despite docker-meta receives "tag-latest: true" as input, the only tags generated are "master".

Also reported it https://github.com/crazy-max/ghaction-docker-meta/issues/40 apparently.

**Comment by crazy-max** [comment]
@felipecrs https://github.com/crazy-max/ghaction-docker-meta#latest-tag

**Comment by felipecrs** [comment]
Got it. The docs says the tag-latest can be disabled if needed, but not deliberately enabled. Is that right?

**Comment by felipecrs** [comment]
I believe the `tag-latest` input should be respected if provided by the user no matter what. To implement that, its default value must not be `true` anymore, then we treat the `undefined` cases.

This is very similar to an old PR I made to the legacy docker action: https://github.com/docker/github-actions/pull/20

**Comment by crazy-max** [comment]
@felipecrs I think you could specify a custom tag as latest in this case with `tag-custom` input. Or maybe we could handle 3 states for `tag-latest`: `auto|true|false`.

**Comment by felipecrs** [comment]
@crazy-max Awesome. May I send a PR?

**Comment by beevelop** [comment]
I experienced the same issue and am actually trying to build the `master` branch as `latest`. If you have a dedicated repository for the Docker builds, you can work around this limitation by renaming the `master` branch to `latest` 🎩

**Comment by felipecrs** [comment]
As an alternative workaround you can do https://github.com/felipecrs/jenkins-agent-dind/commit/1900c95378cd525412d8a86464d3156bd9c2e629.
