### ISSUE TITLE
Feature request: Set individual outputs per input flag

### ISSUE THREAD

**Issue by andy-v-h** [crazy-max/ghaction-docker-meta#46]
Currently, the `outputs.tags` gives a list of all the tags that were pushed. It would be useful if when, for example,  a `tag-sha` is `true`, there was an `outputs.tag-sha` to accompany it. This would enable later steps to use a particular tag. 

The motivation for this is a building an image of an application and picking a particular tag to use for generating a PR to bump the image tag in a Helm chart `values.yaml`

**Comment by crazy-max** [comment]
@andy-v-h LGTM, I will focus on #30 to refactor this action and I keep this feature.

**Comment by crazy-max** [comment]
All things considered I don't see how we could handle this behavior cause inputs from v1 have been merged to [`tags` input in v2](https://github.com/crazy-max/ghaction-docker-meta#tags-input). Maybe you could use the [`version` output](https://github.com/crazy-max/ghaction-docker-meta#outputs) which is the main tag. I'm closing this issue but feel free to leave a comment if you want a better alternative.

**Comment by cdeneen** [comment]
I think this solves what you are trying to do. I think the tag list follows the meta tags list order so if you put your ref tag first...
`${{ fromJson(steps.dockermeta.outputs.json).tags[0]`
