### ISSUE TITLE
Add multiple tags based on semver

### ISSUE THREAD

**Issue by fastlorenzo** [crazy-max/ghaction-docker-meta#6]
It would be great it this action could parse a semver tag and output multiple related docker tags.

Example: for version `1.2.3`, the following tags would be set: `1`, `1.2`, `1.2.3` and `latest`

**Comment by crazy-max** [comment]
@fastlorenzo Sounds good to me, thanks for your input.

**Comment by fastlorenzo** [comment]
@crazy-max any chance you have time to have a look at PR #10 ?
